### PR TITLE
add /summary api endpoint

### PR DESCRIPTION
**Pull request by erubboli-bfx**
- add new API endpoint /summary
- bump version to 0.0.8

### CODE REVIEW

**Comment by prdn** [comment]
Looks good

**Comment by arvicco** [comment]
/summary endpoint does not work for me, always returns Bitfinex::InternalServerError. Also, there is no description for it in API docs.

**Comment by erubboli-bfx** [comment]
@arvicco the endpoint is not live on production server yet, will be announced soon!

**Comment by arvicco** [comment]
OK, thanks!

**Pull request merged**
