### PR TITLE
Implement API V2

### PR DESCRIPTION
**Pull request by erubboli-bfx**
Checklist:
 [X] choose API version from configuration
 [X] REST public endpoints
 [X] REST authentication 
 [X] REST private endpoints
 [X] WS authentication
 [X] WS endpoints

### CODE REVIEW

**Comment by stasbovanenko** [comment]
Spent some time hacking this gem up to API v2 just this week, so review of this update was rather enjoyable. Sadly I can not say the same about results. WS part doesn't work at all in this version. Problem is in a `subId` field, apparently in BTFX dev environment you can pass some subscription ID to server and he will pass it back along with subscription confirmation, but in production this is not a case at least in present moment. I fixed it by rewriting and simplifying WS channels logic, here is a commit, will do Pull Req latter, some polishing still in order

c6d4314fc4c1a7039b754359db5f1d4d167719bd

**Comment by erubboli-bfx** [comment]
@stasbovanenko thank you for testing the code, we're planning to update the production servers soon and it will include the subId to simplify the channel management.  This PR will stay open until then.

**Comment by ilyacherevkov** [comment]
Is `payload = 'AUTH' + nonce + nonce` correct on line 40 websocket_connection.rb?

**Comment by erubboli-bfx** [comment]
it should work on production now, also this closes #38 .

**Pull request merged**
